apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend-projeto:v1
          imagePullPolicy: Never  # Importante: usa a imagem local do Minikube
          ports:
            - containerPort: 3000
