apiVersion: v1
kind: Service
metadata:
  name: monitor-service
spec:
  type: NodePort
  selector:
    app: monitor
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
